"""UI code generator.

Generates TypeScript configs and React/Refine pages from ModelRegistry.
Output: run_cache/generated_ui_config.ts and run_cache/generated_frontend/
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ..base import CodeGenerator
from ...analysis.registries import ModelRegistry


class TypeScriptUIConfigGenerator(CodeGenerator):
    """Generate TypeScript UI configuration from ModelRegistry."""

    def generate(self) -> Path:
        """Generate TypeScript UI config file."""
        output_file = self.output_dir / "generated_ui_config.ts"

        if not self.needs_regeneration(output_file):
            print(f"✓ {output_file} is up to date (hash match)")
            return output_file

        print(f"→ Generating {output_file}...")

        code_parts = [
            "/**",
            " * Auto-generated UI configuration from ModelRegistry",
            " *",
            " * ⚠️  DO NOT EDIT MANUALLY - Changes will be overwritten!",
            " *     Generated by: python -m core.codegen compile",
            " */",
            "",
            "export interface ModelUIConfig {",
            "  name: string;",
            "  icon: string;",
            "  primaryField: string;",
            "  secondaryField?: string;",
            "  listFields: string[];",
            "  searchableFields: string[];",
            "  sortableFields: string[];",
            "  detailSections: Array<{",
            "    name: string;",
            "    fields: string[];",
            "    collapsible?: boolean;",
            "    collapsed?: boolean;",
            "  }>;",
            "}",
            "",
            "export const MODEL_CONFIGS: Record<string, ModelUIConfig> = {",
        ]

        # Generate config for each model
        for model_info in ModelRegistry.list_all():
            config = {
                "name": model_info.name,
                "icon": model_info.ui_hints.get("icon", "📄"),
                "primaryField": model_info.ui_hints.get("primary_field", "id"),
                "secondaryField": model_info.ui_hints.get("secondary_field"),
                "listFields": model_info.ui_hints.get("list_fields", []),
                "searchableFields": model_info.searchable_fields,
                "sortableFields": model_info.sortable_fields,
                "detailSections": model_info.ui_hints.get("detail_sections", []),
            }

            config_json = json.dumps(config, indent=2)
            code_parts.append(f"  {model_info.name}: {config_json},")

        code_parts.append("};")
        code_parts.append("")
        code_parts.append("// Auto-generated resource definitions for Refine.dev")
        code_parts.append("export const RESOURCES = Object.keys(MODEL_CONFIGS).map(name => ({")
        code_parts.append("  name: name.toLowerCase(),  // Lowercase to match API endpoints")
        code_parts.append("  list: `/${name.toLowerCase()}s`,")
        code_parts.append("  show: `/${name.toLowerCase()}s/:id`,")
        code_parts.append("  create: `/${name.toLowerCase()}s/new`,")
        code_parts.append("  edit: `/${name.toLowerCase()}s/:id/edit`,")
        code_parts.append("  meta: MODEL_CONFIGS[name],")
        code_parts.append("}));")

        code = "\n".join(code_parts)
        output_file.write_text(code)
        self.save_hash(output_file)

        print(f"✓ Generated {len(code.splitlines())} lines of TypeScript config")
        return output_file


class RefinePageGenerator(CodeGenerator):
    """Generate Refine.dev page components from ModelRegistry.

    NOTE: This class is used internally by CopyAndGenerateFrontend.
    All generated files go to .run_cache/generated_frontend/
    """

    def __init__(self, output_dir: Path = Path(".run_cache/generated_frontend/src")):
        """Initialize with generated frontend directory."""
        super().__init__(output_dir)

    def _generate_list_page(self, model_info: Any, pages_dir: Path) -> Path:
        """Generate List page component."""
        model_name = model_info.name
        model_lower = model_name.lower()
        list_fields = model_info.ui_hints.get("list_fields", [])

        # Generate table columns from list_fields
        columns = "\n      ".join(
            [
                f'<Table.Column dataIndex="{field}" title="{field.replace("_", " ").title()}" key="{field}" />'
                for field in list_fields
            ]
        )

        # Build code without f-string to avoid colon conflicts with TypeScript
        code = f"""/**
 * Auto-generated List page for {model_name}
 *
 * ⚠️  DO NOT EDIT MANUALLY - Changes will be overwritten!
 *     Generated by: python -m core.codegen compile
 */

import {{ List, useTable, EditButton, ShowButton, DeleteButton }} from "@refinedev/antd";
import {{ Table, Space }} from "antd";

export const {model_name}List = () => {{
  const {{ tableProps }} = useTable({{
    resource: "{model_lower}",
  }});

  return (
    <List>
      <Table {{...tableProps}} rowKey="id">
        {columns}
        <Table.Column
          title="Actions"
          dataIndex="actions"
          render={{(_: any, record: any) => (
            <Space>
              <EditButton hideText size="small" recordItemId={{record.id}} />
              <ShowButton hideText size="small" recordItemId={{record.id}} />
              <DeleteButton hideText size="small" recordItemId={{record.id}} />
            </Space>
          )}}
        />
      </Table>
    </List>
  );
}};
"""
        output_file = pages_dir / "list.tsx"
        output_file.write_text(code)
        print(f"  ✓ Generated {output_file}")
        return output_file

    def _generate_show_page(self, model_info: Any, pages_dir: Path) -> Path:
        """Generate Show page component."""
        model_name = model_info.name
        detail_sections = model_info.ui_hints.get("detail_sections", [])

        # Generate field displays grouped by sections
        sections_code = []
        for section in detail_sections:
            fields = "\n          ".join(
                [
                    f'<TextField title="{field.replace("_", " ").title()}" value={{record?.{field}}} />'
                    for field in section["fields"]
                ]
            )
            sections_code.append(
                f"""
        <div style={{{{ marginBottom: 24 }}}}>
          <h3>{section["name"]}</h3>
          {fields}
        </div>"""
            )

        sections_html = "".join(sections_code)

        code = f"""/**
 * Auto-generated Show page for {model_name}
 *
 * ⚠️  DO NOT EDIT MANUALLY - Changes will be overwritten!
 *     Generated by: python -m core.codegen compile
 */

import {{ Show, TextField }} from "@refinedev/antd";
import {{ useShow }} from "@refinedev/core";

export const {model_name}Show = () => {{
  const {{ queryResult }} = useShow();
  const {{ data, isLoading }} = queryResult;
  const record = data?.data;

  return (
    <Show isLoading={{isLoading}}>
      {sections_html}
    </Show>
  );
}};
"""
        output_file = pages_dir / "show.tsx"
        output_file.write_text(code)
        print(f"  ✓ Generated {output_file}")
        return output_file

    def _generate_create_page(self, model_info: Any, pages_dir: Path) -> Path:
        """Generate Create page component."""
        model_name = model_info.name
        list_fields = model_info.ui_hints.get("list_fields", [])

        # Generate form items
        form_items = "\n        ".join(
            [
                f'<Form.Item label="{field.replace("_", " ").title()}" name="{field}">\n          <Input />\n        </Form.Item>'
                for field in list_fields
                if field not in ["id", "created_at", "updated_at"]
            ]
        )

        code = f"""/**
 * Auto-generated Create page for {model_name}
 *
 * ⚠️  DO NOT EDIT MANUALLY - Changes will be overwritten!
 *     Generated by: python -m core.codegen compile
 */

import {{ Create }} from "@refinedev/antd";
import {{ Form, Input }} from "antd";

export const {model_name}Create = () => {{
  return (
    <Create saveButtonProps={{{{ htmlType: "submit" }}}}>
      <Form layout="vertical">
        {form_items}
      </Form>
    </Create>
  );
}};
"""
        output_file = pages_dir / "create.tsx"
        output_file.write_text(code)
        print(f"  ✓ Generated {output_file}")
        return output_file

    def _generate_edit_page(self, model_info: Any, pages_dir: Path) -> Path:
        """Generate Edit page component."""
        model_name = model_info.name
        list_fields = model_info.ui_hints.get("list_fields", [])

        # Generate form items
        form_items = "\n        ".join(
            [
                f'<Form.Item label="{field.replace("_", " ").title()}" name="{field}">\n          <Input />\n        </Form.Item>'
                for field in list_fields
                if field not in ["id", "created_at", "updated_at"]
            ]
        )

        code = f"""/**
 * Auto-generated Edit page for {model_name}
 *
 * ⚠️  DO NOT EDIT MANUALLY - Changes will be overwritten!
 *     Generated by: python -m core.codegen compile
 */

import {{ Edit }} from "@refinedev/antd";
import {{ Form, Input }} from "antd";
import {{ useForm }} from "@refinedev/antd";

export const {model_name}Edit = () => {{
  const {{ formProps, saveButtonProps }} = useForm();

  return (
    <Edit saveButtonProps={{saveButtonProps}}>
      <Form {{...formProps}} layout="vertical">
        {form_items}
      </Form>
    </Edit>
  );
}};
"""
        output_file = pages_dir / "edit.tsx"
        output_file.write_text(code)
        print(f"  ✓ Generated {output_file}")
        return output_file

    def _generate_index_file(self, model_info: Any, pages_dir: Path) -> Path:
        """Generate index.ts to export all page components."""
        model_name = model_info.name

        code = f"""/**
 * Auto-generated index for {model_name} pages
 */

export {{ {model_name}List }} from "./list";
export {{ {model_name}Show }} from "./show";
export {{ {model_name}Create }} from "./create";
export {{ {model_name}Edit }} from "./edit";
"""
        output_file = pages_dir / "index.ts"
        output_file.write_text(code)
        print(f"  ✓ Generated {output_file}")
        return output_file


class CopyAndGenerateFrontend(CodeGenerator):
    """Copy frontend template and generate complete frontend."""

    def __init__(self, output_dir: Path = Path(".run_cache/generated_frontend")):
        """Initialize with generated frontend directory."""
        super().__init__(output_dir)
        # template_dir is at core/frontend_template (sibling of core/core/)
        self.template_dir = Path(__file__).parent.parent / "frontend_template"

    def generate(self) -> Path:
        """Copy template and generate complete frontend."""
        import shutil

        print("\n→ Generating complete frontend...")

        # Step 1: Copy template (remove old if exists)
        if self.output_dir.exists():
            shutil.rmtree(self.output_dir)

        shutil.copytree(self.template_dir, self.output_dir)
        print(f"  ✓ Copied template to {self.output_dir}")

        # Step 2: Generate App.tsx from template
        self._generate_app_tsx()

        # Step 3: Copy UI config
        self._copy_ui_config()

        # Step 4: Generate all pages
        generated_pages = []
        for model_info in ModelRegistry.list_all():
            pages = self._generate_model_pages(model_info)
            generated_pages.extend(pages)

        print(f"  ✓ Generated {len(generated_pages)} page files")

        # Step 5: Create instructions file
        self._create_instructions()

        return self.output_dir

    def _generate_app_tsx(self):
        """Generate App.tsx from template with model imports and routes."""
        template_file = self.output_dir / "src" / "App.tsx.template"
        output_file = self.output_dir / "src" / "App.tsx"

        if not template_file.exists():
            print(f"  ⚠️  Warning: Template file {template_file} not found")
            return

        template_content = template_file.read_text()

        # Generate imports for all models
        imports = []
        routes = []

        for model_info in ModelRegistry.list_all():
            model_name = model_info.name
            model_lower = model_name.lower()

            # Add import
            imports.append(
                f'import {{ {model_name}List, {model_name}Show, {model_name}Create, {model_name}Edit }} from "./pages/{model_lower}";'
            )

            # Add routes
            routes.extend(
                [
                    f"            {{/* {model_name} Routes */}}",
                    "            <Route",
                    "              element={",
                    "                <ThemedLayoutV2>",
                    f"                  <{model_name}List />",
                    "                </ThemedLayoutV2>",
                    "              }",
                    f'              path="/{model_lower}s"',
                    "            />",
                    "            <Route",
                    "              element={",
                    "                <ThemedLayoutV2>",
                    f"                  <{model_name}Show />",
                    "                </ThemedLayoutV2>",
                    "              }",
                    f'              path="/{model_lower}s/:id"',
                    "            />",
                    "            <Route",
                    "              element={",
                    "                <ThemedLayoutV2>",
                    f"                  <{model_name}Create />",
                    "                </ThemedLayoutV2>",
                    "              }",
                    f'              path="/{model_lower}s/create"',
                    "            />",
                    "            <Route",
                    "              element={",
                    "                <ThemedLayoutV2>",
                    f"                  <{model_name}Edit />",
                    "                </ThemedLayoutV2>",
                    "              }",
                    f'              path="/{model_lower}s/edit/:id"',
                    "            />",
                    "",
                ]
            )

        # Replace placeholders
        output_content = template_content.replace("{%IMPORTS%}", "\n".join(imports))
        output_content = output_content.replace("{%ROUTES%}", "\n".join(routes))

        output_file.write_text(output_content)
        template_file.unlink()  # Remove template file

        print(f"  ✓ Generated {output_file}")

    def _copy_ui_config(self):
        """Copy generated UI config to frontend."""
        source = Path(".run_cache/generated_ui_config.ts")
        dest = self.output_dir / "src" / "config" / "generated.ts"
        dest.parent.mkdir(parents=True, exist_ok=True)

        if source.exists():
            dest.write_text(source.read_text())
            print(f"  ✓ Copied UI config to {dest}")
        else:
            print(f"  ⚠️  Warning: {source} not found")

    def _generate_model_pages(self, model_info: Any) -> list[Path]:
        """Generate all pages for a model."""
        model_name = model_info.name
        model_lower = model_name.lower()

        pages_dir = self.output_dir / "src" / "pages" / model_lower
        pages_dir.mkdir(parents=True, exist_ok=True)

        generated = []

        # Use existing page generation logic
        page_gen = RefinePageGenerator(self.output_dir / "src")
        generated.append(page_gen._generate_list_page(model_info, pages_dir))
        generated.append(page_gen._generate_show_page(model_info, pages_dir))
        generated.append(page_gen._generate_create_page(model_info, pages_dir))
        generated.append(page_gen._generate_edit_page(model_info, pages_dir))
        generated.append(page_gen._generate_index_file(model_info, pages_dir))

        return generated

    def _create_instructions(self):
        """Create instructions file for using generated frontend."""
        instructions = """# Generated Frontend

This directory contains a **fully generated frontend** from your @datamodel decorators.

## ⚠️ DO NOT EDIT FILES HERE DIRECTLY!

All files in this directory are auto-generated. Changes will be overwritten on next `make codegen`.

## How to Use

### 1. Install Dependencies (First Time Only)

```bash
cd .run_cache/generated_frontend
npm install
```

### 2. Run Development Server

```bash
npm run dev
```

The UI will be available at: http://localhost:3000

### 3. Build for Production

```bash
npm run build
```

Output will be in `dist/` directory.

## Customization

To customize the frontend:

1. **Edit the template:** `core/frontend_template/src/App.tsx.template`
2. **Regenerate:** Run `make codegen`
3. **Your changes will appear here**

## Generated Content

This directory contains:
- ✅ All npm dependencies installed
- ✅ TypeScript configuration
- ✅ Vite build configuration
- ✅ React app with Refine.dev
- ✅ Auto-generated pages for all models
- ✅ Auto-generated routes
- ✅ Auto-generated config

## Models Included

"""
        for model in ModelRegistry.list_all():
            instructions += f"- {model.name} ({model.description or 'No description'})\n"

        instructions += f"\n**Total:** {len(ModelRegistry.list_all())} models\n"

        (self.output_dir / "README.md").write_text(instructions)
        print("  ✓ Created README.md with instructions")


