#!/usr/bin/env python3
"""Generate a comprehensive project CLI with all operational commands.

Generates: ./<project_name> (executable)

The generated CLI includes:
- Services management (up, down, restart, logs, status, health)
- Operations execution (ops run, ops list)
- Database management (db init, seed, backup, restore)
- Prefect workflows (prefect start, stop, run)
- Development tools (api, ui)
- Regeneration (compile)
"""

from __future__ import annotations

from textwrap import dedent, indent

from ...analysis.registries import OperationRegistry, ModelRegistry


def generate_cli_script(project_name: str = "main") -> str:
    """Generate complete project CLI script.

    Args:
        project_name: Name of the project

    Returns:
        Complete CLI script as string
    """
    operations = OperationRegistry.list_all()
    models = ModelRegistry.list_all()

    # Build operations data
    ops_list = []
    for op in operations:
        ops_list.append(f"""        {{
            "name": "{op.name}",
            "description": "{op.description or 'No description'}",
            "category": "{op.category or 'general'}",
            "input": "{op.input_schema.__name__}",
            "output": "{op.output_schema.__name__}",
        }}""")

    operations_data = "[\n" + ",\n".join(ops_list) + "\n    ]" if ops_list else "[]"

    # Build models data
    models_list = []
    for m in models:
        models_list.append(f"""        {{
            "name": "{m.name}",
            "description": "{m.description or 'No description'}",
        }}""")

    models_data = "[\n" + ",\n".join(models_list) + "\n    ]" if models_list else "[]"

    cli_script = f'''#!/usr/bin/env python3
"""Project CLI - Generated by Pulpo.

⚠️  DO NOT EDIT MANUALLY - Changes will be overwritten!
    Regenerate with: pulpo compile

This CLI provides operational commands for the project:
- Services: up, down, restart, logs, status, health
- Operations: ops run, ops list
- Database: db init, seed, backup, restore
- Prefect: prefect start, stop, run
- Development: api, ui
- Regeneration: compile
"""

import sys
import json
import subprocess
from pathlib import Path
from typing import Optional

# Metadata (from registries at compile time)
PROJECT_NAME = "{project_name}"
OPERATIONS = {operations_data}
MODELS = {models_data}


# =============================================================================
# UTILITIES
# =============================================================================

def run_command(cmd: list[str], capture: bool = False) -> Optional[str]:
    """Run a shell command."""
    try:
        if capture:
            result = subprocess.run(cmd, capture_output=True, text=True, check=True)
            return result.stdout
        else:
            subprocess.run(cmd, check=True)
            return None
    except subprocess.CalledProcessError as e:
        print(f"❌ Command failed: {{' '.join(cmd)}}")
        print(f"Error: {{e}}")
        sys.exit(1)
    except FileNotFoundError:
        print(f"❌ Command not found: {{cmd[0]}}")
        print("Make sure Docker/docker-compose is installed")
        sys.exit(1)


def print_header(text: str):
    """Print a header."""
    print(f"\\n{'='*60}")
    print(f"  {{text}}")
    print(f"{'='*60}\\n")


def print_success(text: str):
    """Print success message."""
    print(f"✅ {{text}}")


def print_error(text: str):
    """Print error message."""
    print(f"❌ {{text}}")


def print_info(text: str):
    """Print info message."""
    print(f"ℹ️  {{text}}")


# =============================================================================
# SERVICES COMMANDS
# =============================================================================

def services_up():
    """Start all Docker services."""
    print_header("Starting Services")
    print_info("Starting MongoDB, API, UI, Prefect Server, Prefect Worker...")
    run_command(["docker-compose", "up", "-d"])
    print_success("All services started")
    print("\\nAccess:")
    print("  📡 API:     http://localhost:8000/docs")
    print("  🎨 UI:      http://localhost:3000")
    print("  🔮 Prefect: http://localhost:4200")


def services_down():
    """Stop all Docker services."""
    print_header("Stopping Services")
    run_command(["docker-compose", "down"])
    print_success("All services stopped")


def services_restart():
    """Restart all Docker services."""
    print_header("Restarting Services")
    services_down()
    services_up()


def services_logs(service: Optional[str] = None, follow: bool = False):
    """Show logs for services."""
    print_header(f"Logs{{' (following)' if follow else ''}}")
    cmd = ["docker-compose", "logs"]
    if follow:
        cmd.append("-f")
    if service:
        cmd.append(service)
    run_command(cmd)


def services_status():
    """Show status of all services."""
    print_header("Services Status")
    run_command(["docker-compose", "ps"])


def services_health():
    """Check health of all services."""
    print_header("Health Check")
    # Check each service
    services = ["api", "mongodb", "prefect-server"]
    for svc in services:
        try:
            result = subprocess.run(
                ["docker-compose", "ps", "-q", svc],
                capture_output=True,
                text=True,
                check=True
            )
            if result.stdout.strip():
                print_success(f"{{svc}}: Running")
            else:
                print_error(f"{{svc}}: Not running")
        except Exception:
            print_error(f"{{svc}}: Unknown")


# =============================================================================
# OPERATIONS COMMANDS
# =============================================================================

def ops_list(category: Optional[str] = None):
    """List all operations."""
    print_header("Operations")

    if not OPERATIONS:
        print_info("No operations registered")
        return

    # Group by category
    by_category = {{}}
    for op in OPERATIONS:
        cat = op.get("category", "general")
        if cat not in by_category:
            by_category[cat] = []
        by_category[cat].append(op)

    # Filter by category if specified
    if category:
        by_category = {{k: v for k, v in by_category.items() if k == category}}

    # Print
    for cat, ops in sorted(by_category.items()):
        print(f"\\n📁 {{cat.upper()}}:")
        for op in ops:
            print(f"  • {{op['name']:<30}} - {{op['description']}}")

    print(f"\\n📊 Total: {{len(OPERATIONS)}} operations")


def ops_show(name: str):
    """Show details for a specific operation."""
    for op in OPERATIONS:
        if op["name"] == name:
            print_header(f"Operation: {{name}}")
            print(f"Description: {{op['description']}}")
            print(f"Category:    {{op['category']}}")
            print(f"Input:       {{op['input']}}")
            print(f"Output:      {{op['output']}}")
            return

    print_error(f"Operation '{{name}}' not found")
    sys.exit(1)


def ops_run(name: str, input_data: Optional[str] = None, input_file: Optional[str] = None):
    """Execute an operation."""
    # Verify operation exists
    op_exists = any(op["name"] == name for op in OPERATIONS)
    if not op_exists:
        print_error(f"Operation '{{name}}' not found")
        print_info("Run './{{PROJECT_NAME}} ops list' to see available operations")
        sys.exit(1)

    print_header(f"Executing: {{name}}")

    # Prepare input
    if input_file:
        with open(input_file) as f:
            input_json = f.read()
    elif input_data:
        input_json = input_data
    else:
        input_json = "{{}}"

    # Call API endpoint
    import urllib.request
    import urllib.error

    try:
        url = f"http://localhost:8000/api/v1/operations/{{name}}"
        req = urllib.request.Request(
            url,
            data=input_json.encode(),
            headers={{"Content-Type": "application/json"}},
            method="POST"
        )

        with urllib.request.urlopen(req) as response:
            result = json.loads(response.read().decode())
            print_success("Operation completed")
            print("\\nResult:")
            print(json.dumps(result, indent=2))

    except urllib.error.URLError:
        print_error("Cannot connect to API server")
        print_info("Make sure services are running: ./{{PROJECT_NAME}} up")
        sys.exit(1)
    except Exception as e:
        print_error(f"Execution failed: {{e}}")
        sys.exit(1)


# =============================================================================
# DATABASE COMMANDS
# =============================================================================

def db_init():
    """Initialize database schema."""
    print_header("Database Initialization")
    print_info("Initializing schema and indexes...")
    run_command(["docker-compose", "exec", "mongodb", "mongosh", "--eval", "db.version()"])
    print_success("Database initialized")


def db_seed():
    """Seed test data."""
    print_header("Database Seeding")
    print_info("Seeding test data...")
    # TODO: Implement actual seeding
    print_info("Seeding not yet implemented")


def db_backup(filename: Optional[str] = None):
    """Backup database."""
    print_header("Database Backup")
    if not filename:
        from datetime import datetime
        filename = f"backup-{{datetime.now().strftime('%Y%m%d-%H%M%S')}}.gz"

    print_info(f"Backing up to: {{filename}}")
    Path("backups").mkdir(exist_ok=True)
    run_command([
        "docker-compose", "exec", "-T", "mongodb",
        "mongodump", "--archive", "--gzip"
    ])
    print_success(f"Backup saved: backups/{{filename}}")


def db_restore(filename: str):
    """Restore from backup."""
    print_header("Database Restore")
    backup_path = Path("backups") / filename
    if not backup_path.exists():
        print_error(f"Backup not found: {{backup_path}}")
        sys.exit(1)

    print_info(f"Restoring from: {{filename}}")
    # TODO: Implement actual restore
    print_info("Restore not yet implemented")


def db_shell():
    """Open MongoDB shell."""
    print_header("MongoDB Shell")
    run_command(["docker-compose", "exec", "mongodb", "mongosh"])


# =============================================================================
# PREFECT COMMANDS
# =============================================================================

def prefect_start():
    """Start Prefect server."""
    print_header("Starting Prefect")
    run_command(["docker-compose", "up", "-d", "prefect-server", "prefect-worker"])
    print_success("Prefect started")
    print_info("UI: http://localhost:4200")


def prefect_stop():
    """Stop Prefect server."""
    print_header("Stopping Prefect")
    run_command(["docker-compose", "stop", "prefect-server", "prefect-worker"])
    print_success("Prefect stopped")


def prefect_ui():
    """Open Prefect UI."""
    import webbrowser
    webbrowser.open("http://localhost:4200")
    print_info("Opening Prefect UI in browser...")


def prefect_logs():
    """Show Prefect logs."""
    print_header("Prefect Logs")
    run_command(["docker-compose", "logs", "-f", "prefect-server", "prefect-worker"])


# =============================================================================
# DEVELOPMENT COMMANDS
# =============================================================================

def dev_api(port: int = 8000):
    """Run API locally (development mode)."""
    print_header("Development API Server")
    print_info(f"Starting API on http://localhost:{{port}}")
    print_info("Press Ctrl+C to stop")
    run_command(["uvicorn", "run_cache.generated_api:app", "--reload", "--port", str(port)])


def dev_ui(port: int = 3000):
    """Run UI locally (development mode)."""
    print_header("Development UI Server")
    print_info(f"Starting UI on http://localhost:{{port}}")
    print_info("Press Ctrl+C to stop")
    frontend_dir = Path("run_cache/generated_frontend")
    if not frontend_dir.exists():
        print_error("Frontend not generated. Run: ./{{PROJECT_NAME}} compile")
        sys.exit(1)

    import os
    os.chdir(frontend_dir)
    run_command(["npm", "start"])


# =============================================================================
# UTILITY COMMANDS
# =============================================================================

def compile_code():
    """Regenerate code (delegates to framework CLI)."""
    print_header("Code Regeneration")
    print_info("Calling: pulpo compile")
    run_command(["pulpo", "compile"])
    print_success("Code regenerated")


def show_version():
    """Show version info."""
    print(f"\\n{{PROJECT_NAME}} CLI (Generated by Pulpo)")
    print(f"Project: {{PROJECT_NAME}}")
    print(f"Models: {{len(MODELS)}}")
    print(f"Operations: {{len(OPERATIONS)}}")


def show_help():
    """Show help message."""
    help_text = f"""
{{PROJECT_NAME}} - Project CLI

USAGE:
    ./{{PROJECT_NAME}} <command> [arguments]

SERVICES:
    up              Start all Docker services
    down            Stop all services
    restart         Restart all services
    logs [service]  Show logs (optional: specific service)
    status          Show status of all services
    health          Health check for all services

OPERATIONS:
    ops list [--category <cat>]       List all operations
    ops show <name>                    Show operation details
    ops run <name> [--input <json>]    Execute operation
    ops run <name> --input-file <path> Execute with file input

DATABASE:
    db init                    Initialize schema
    db seed                    Seed test data
    db backup [filename]       Backup database
    db restore <filename>      Restore from backup
    db shell                   Open MongoDB shell

PREFECT:
    prefect start              Start Prefect server
    prefect stop               Stop Prefect server
    prefect ui                 Open Prefect UI
    prefect logs               Show Prefect logs

DEVELOPMENT:
    api [--port <port>]        Run API locally (dev mode)
    ui [--port <port>]         Run UI locally (dev mode)

UTILITIES:
    compile                    Regenerate code (calls: pulpo compile)
    version                    Show version info
    help                       Show this help

EXAMPLES:
    ./{{PROJECT_NAME}} up
    ./{{PROJECT_NAME}} ops list
    ./{{PROJECT_NAME}} ops run create_user --input '{{"email":"test@test.com"}}'
    ./{{PROJECT_NAME}} logs --follow
    ./{{PROJECT_NAME}} db shell
    ./{{PROJECT_NAME}} compile

For more info: https://docs.pulpo.dev
    """
    print(help_text)


# =============================================================================
# MAIN
# =============================================================================

def main():
    """Main CLI entry point."""
    if len(sys.argv) < 2:
        show_help()
        return

    command = sys.argv[1]
    args = sys.argv[2:]

    # Parse command
    try:
        # Services
        if command == "up":
            services_up()
        elif command == "down":
            services_down()
        elif command == "restart":
            services_restart()
        elif command == "logs":
            follow = "--follow" in args or "-f" in args
            service = args[0] if args and not args[0].startswith("--") else None
            services_logs(service, follow)
        elif command == "status":
            services_status()
        elif command == "health":
            services_health()

        # Operations
        elif command == "ops":
            if not args:
                print_error("ops requires a subcommand")
                print_info("Available: list, show, run")
                sys.exit(1)

            subcmd = args[0]
            if subcmd == "list":
                category = args[2] if len(args) > 2 and args[1] == "--category" else None
                ops_list(category)
            elif subcmd == "show":
                if len(args) < 2:
                    print_error("ops show requires operation name")
                    sys.exit(1)
                ops_show(args[1])
            elif subcmd == "run":
                if len(args) < 2:
                    print_error("ops run requires operation name")
                    sys.exit(1)

                name = args[1]
                input_data = None
                input_file = None

                for i, arg in enumerate(args[2:], 2):
                    if arg == "--input" and i + 1 < len(args):
                        input_data = args[i + 1]
                    elif arg == "--input-file" and i + 1 < len(args):
                        input_file = args[i + 1]

                ops_run(name, input_data, input_file)
            else:
                print_error(f"Unknown ops subcommand: {{subcmd}}")
                sys.exit(1)

        # Database
        elif command == "db":
            if not args:
                print_error("db requires a subcommand")
                print_info("Available: init, seed, backup, restore, shell")
                sys.exit(1)

            subcmd = args[0]
            if subcmd == "init":
                db_init()
            elif subcmd == "seed":
                db_seed()
            elif subcmd == "backup":
                filename = args[1] if len(args) > 1 else None
                db_backup(filename)
            elif subcmd == "restore":
                if len(args) < 2:
                    print_error("db restore requires backup filename")
                    sys.exit(1)
                db_restore(args[1])
            elif subcmd == "shell":
                db_shell()
            else:
                print_error(f"Unknown db subcommand: {{subcmd}}")
                sys.exit(1)

        # Prefect
        elif command == "prefect":
            if not args:
                print_error("prefect requires a subcommand")
                print_info("Available: start, stop, ui, logs")
                sys.exit(1)

            subcmd = args[0]
            if subcmd == "start":
                prefect_start()
            elif subcmd == "stop":
                prefect_stop()
            elif subcmd == "ui":
                prefect_ui()
            elif subcmd == "logs":
                prefect_logs()
            else:
                print_error(f"Unknown prefect subcommand: {{subcmd}}")
                sys.exit(1)

        # Development
        elif command == "api":
            port = 8000
            if "--port" in args:
                port_idx = args.index("--port")
                if port_idx + 1 < len(args):
                    port = int(args[port_idx + 1])
            dev_api(port)

        elif command == "ui":
            port = 3000
            if "--port" in args:
                port_idx = args.index("--port")
                if port_idx + 1 < len(args):
                    port = int(args[port_idx + 1])
            dev_ui(port)

        # Utilities
        elif command == "compile":
            compile_code()
        elif command == "version":
            show_version()
        elif command in ("help", "--help", "-h"):
            show_help()

        else:
            print_error(f"Unknown command: {{command}}")
            print_info("Run './{{PROJECT_NAME}} help' for available commands")
            sys.exit(1)

    except KeyboardInterrupt:
        print("\\n\\nInterrupted by user")
        sys.exit(0)
    except Exception as e:
        print_error(f"Unexpected error: {{e}}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
'''

    return cli_script


__all__ = ["generate_cli_script"]
