#!/usr/bin/env python3
"""Run the auto-generated API server.

This script starts the FastAPI application generated by the core framework.
The generated API includes:
- CRUD endpoints for all @datamodel decorated models
- Custom endpoints from @operation decorated functions
- Auto-generated TypeScript types and Refine.dev configuration

Generated files are located in: .run_cache/generated_api/
"""

import uvicorn

if __name__ == "__main__":
    print("\n" + "=" * 80)
    print("🚀 Core Framework - Auto-Generated API")
    print("=" * 80)
    print("")
    print("📚 API Documentation: http://localhost:8000/docs")
    print("🏥 Health Check:      http://localhost:8000/health")
    print("🔌 API Base URL:      http://localhost:8000/api/v1")
    print("")
    print("⚠️  Requirements:")
    print("   • MongoDB running on localhost:27017")
    print("   • Generated API code (.run_cache/generated_api/)")
    print("   • Python dependencies installed (poetry install)")
    print("")
    print("To start MongoDB:")
    print("   docker run -d -p 27017:27017 -v mongo-data:/data/db mongo:latest")
    print("")
    print("Starting server...")
    print("=" * 80)
    print("")

    uvicorn.run(
        ".run_cache.generated_api:app",
        host="0.0.0.0",
        port=8000,
        reload=True,
        reload_dirs=["core", ".run_cache"],
    )
